version: '3.1'
services:
  api:
    build: ./dev.Dockerfile
    image: langchat-api:latest
    container_name: langchat-api
    depends_on:
      - mongo
    ports:
      - 8080:80
    environment:
      - OPENAI_API_KEY=''
      - NOVU_API_KEY=''
      - MONGODB_CONNECTION_URL='mongodb://root:example@mongo:27017/'
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
  webapp:
    build: ./ui.dev.Dockerfile
    image: langchat-ui:latest
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false