// This file is auto-generated by @hey-api/openapi-ts

export type Chat = {
    user_id: string;
    chat_id: string;
    messages: Array<ChatMessage>;
};

export type ChatMessage = {
    content: string;
    role: string;
    id: string;
    timestamp?: string | null;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CreateChatApiV1ChatsPostResponse = Chat;

export type ListChatsApiV1ChatsGetResponse = Array<Chat>;

export type GetChatApiV1ChatsChatIdGetData = {
    chatId: string;
};

export type GetChatApiV1ChatsChatIdGetResponse = Chat;

export type DeleteChatApiV1ChatsChatIdDeleteData = {
    chatId: string;
};

export type DeleteChatApiV1ChatsChatIdDeleteResponse = string;

export type AddMessageApiV1ChatsChatIdMessagesPostData = {
    chatId: string;
    requestBody: ChatMessage;
};

export type AddMessageApiV1ChatsChatIdMessagesPostResponse = string;

export type ListMessagesApiV1ChatsChatIdMessagesGetData = {
    chatId: string;
};

export type ListMessagesApiV1ChatsChatIdMessagesGetResponse = Array<ChatMessage>;

export type GetMessageApiV1ChatsChatIdMessagesMessageIdGetData = {
    chatId: string;
    messageId: string;
};

export type GetMessageApiV1ChatsChatIdMessagesMessageIdGetResponse = ChatMessage;

export type DeleteMessageApiV1ChatsChatIdMessagesMessageIdDeleteData = {
    chatId: string;
    messageId: string;
};

export type DeleteMessageApiV1ChatsChatIdMessagesMessageIdDeleteResponse = string;

export type UpdateMessageContentApiV1ChatsChatIdMessagesMessageIdContentPutData = {
    chatId: string;
    content: string;
    messageId: string;
};

export type UpdateMessageContentApiV1ChatsChatIdMessagesMessageIdContentPutResponse = string;

export type $OpenApiTs = {
    '/api/v1/chats/': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: Chat;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/chats': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Chat>;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/chats/{chat_id}': {
        get: {
            req: GetChatApiV1ChatsChatIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Chat;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteChatApiV1ChatsChatIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/chats/{chat_id}/messages/': {
        post: {
            req: AddMessageApiV1ChatsChatIdMessagesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        get: {
            req: ListMessagesApiV1ChatsChatIdMessagesGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ChatMessage>;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/chats/{chat_id}/messages/{message_id}': {
        get: {
            req: GetMessageApiV1ChatsChatIdMessagesMessageIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChatMessage;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteMessageApiV1ChatsChatIdMessagesMessageIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/chats/{chat_id}/messages/{message_id}/content': {
        put: {
            req: UpdateMessageContentApiV1ChatsChatIdMessagesMessageIdContentPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Unauthorized or limited access
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};